blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ Questions & Discussions
    url: https://github.com/SvenVw/rvo-connector/discussions
    about: Please ask questions and discuss ideas here.
  - name: ğŸ” Security Vulnerabilities
    url: https://github.com/SvenVw/rvo-connector/security/advisories/new
    about: Please report security vulnerabilities here.
